/**
 * Artifacts data loader for /dataset page
 * Reads from public/data/artifacts/ (generated by Phase 4 scripts)
 * Also includes Phase 2A loaders for /research page
 * 
 * All loaders use graceful fallbacks - missing artifacts show warnings but don't break builds
 */

import fs from 'node:fs';
import path from 'node:path';

// ============================================================================
// Type definitions
// ============================================================================

// Phase 2A artifact types
export interface ActivityRegime {
  bin: string;
  posts_range: string;
  n_entries: number;
  share_pct: number;
  median_spread_bps?: number;
  median_liq_global_pct?: number;
  median_liq_self_pct?: number;
}

export interface ActivityRegimesData {
  generated_at_utc: string;
  entries_scanned: number;
  total_binned: number;
  source: {
    sample_file: string;
    ssot_file: string;
  };
  fields_used: Record<string, string | null>;
  unavailable_fields: Array<{ field: string; reason: string }>;
  regimes: ActivityRegime[];
}

export interface SamplingDensityData {
  generated_at_utc: string;
  entries_scanned: number;
  source: {
    sample_file: string;
    ssot_file: string;
  };
  fields_used: Record<string, string | null>;
  sample_count_stats: {
    n_entries: number;
    median: number | null;
    p10: number | null;
    p90: number | null;
    min: number | null;
    max: number | null;
  };
  sample_count_histogram: Array<{
    bucket: string;
    count: number;
    share_pct: number;
  }>;
  spot_prices_len_stats: {
    n_entries: number;
    median: number | null;
    p10: number | null;
    p90: number | null;
    min: number | null;
    max: number | null;
  };
  unavailable_fields: Array<{ field: string; reason: string }>;
}

export interface SessionLifecycleData {
  generated_at_utc: string;
  entries_scanned: number;
  source: {
    sample_file: string;
    ssot_file: string;
  };
  definition: {
    session: string;
    typical_duration: string;
  };
  fields_used: Record<string, string | null>;
  duration_stats: {
    n_entries_with_duration: number;
    duration_sec: {
      median: number | null;
      p10: number | null;
      p90: number | null;
      min: number | null;
      max: number | null;
    };
  };
  admission_hour_distribution: Array<{
    hour: number;
    count: number;
  }> | null;
  unavailable_fields: Array<{ field: string; reason: string }>;
  note_sample_bias?: string;
}

// Phase 3A artifact types
export interface DatasetOverviewData {
  generated_at_utc: string;
  scale: {
    entries_scanned: number;
    distinct_symbols: number;
    date_range_utc: string;
    last_entry_ts_utc?: string;
  };
  freshness: {
    archive_sample_source: string;
    notes: string;
  };
  preview_row: {
    symbol: string;
    spread_bps: number;
    liq_global_pct: number;
    posts_total: number;
    mean_score?: number;
  } | null;
  non_claims_block: string[];
}

export interface ArtifactsReadyData {
  status: 'PASS' | 'FAIL';
  generated_at_utc: string;
  artifacts_verified: string[];
  checks_passed: string[];
  warnings: string[];
  errors: string[];
  ready_for_website: boolean;
}

export interface CoverageGroup {
  group_name: string;
  present_rate: number;
  notes?: string;
  example_metric?: string;
}

export interface CoverageData {
  generated_at_utc?: string;
  counts: {
    v7_seen: number;
    v7_usable: number;
  };
  groups: CoverageGroup[];
}

export interface ScaleData {
  generated_at_utc?: string;
  days_running: number;
  v7_usable_total: number;
  avg_usable_per_day: number;
  distinct_symbols_total: number;
  cycles_completed?: number;
  date_range: {
    first_day: string;
    last_day: string;
  };
}

export interface PreviewRowData {
  generated_at_utc?: string;
  note?: string;
  row: Record<string, any>;
}

export interface SentimentBin {
  bin_label: string;
  sample_count: number;
  median: number | null;
  p25: number | null;
  p75: number | null;
  pct_positive: number | null;
}

export interface SentimentVsReturnData {
  description: string;
  coverage: {
    total_usable_entries: number;
    entries_with_mean_score: number;
    entries_with_forward_return: number;
  };
  bins: SentimentBin[];
}

export interface RegimeStats {
  count: number;
  median: number | null;
  p90: number | null;
}

export interface RegimeGroup {
  sample_count: number;
  abs_return_over_window: RegimeStats;
  liq_qv_usd: RegimeStats;
  spread_bps: RegimeStats;
  liq_global_pct: RegimeStats;
}

export interface RegimesData {
  description: string;
  date_range: {
    first: string;
    last: string;
    days: number;
  } | null;
  groups: {
    silent: RegimeGroup;
    active: RegimeGroup;
  };
}

export interface DecisionSource {
  count: number;
  percentage: number;
}

export interface HybridDecisionsData {
  description: string;
  coverage: {
    total_usable_entries: number;
    entries_with_decision_sources: number;
  };
  decision_sources: {
    primary_lexicon: DecisionSource;
    primary_ai: DecisionSource;
    referee_override: DecisionSource;
    full_agreement: DecisionSource;
    total: number;
  };
  posts_scored: {
    total: number;
    entries_with_posts: number;
  };
}

export interface ConfidenceBin {
  bin_label: string;
  sample_count: number;
  disagreement_count: number;
  disagreement_rate: number | null;
}

export interface ConfidenceDisagreementData {
  description: string;
  coverage: {
    total_usable_entries: number;
    entries_with_referee_conf: number;
  };
  bins: ConfidenceBin[];
}

export interface LifecycleSymbol {
  symbol: string;
  sessions_count: number;
  median_duration_sec: number | null;
  first_seen_day: string | null;
  last_seen_day: string | null;
  median_final_score: number | null;
}

export interface LifecycleSummaryData {
  description: string;
  symbols_count: number;
  symbols: LifecycleSymbol[];
}

export interface ArtifactsLoadResult {
  available: boolean;
  warnings: string[];
  ready: ArtifactsReadyData | null;
  coverage: CoverageData | null;
  scale: ScaleData | null;
  preview: PreviewRowData | null;
  sentiment: SentimentVsReturnData | null;
  regimes: RegimesData | null;
  hybrid: HybridDecisionsData | null;
  confidence: ConfidenceDisagreementData | null;
  lifecycle: LifecycleSummaryData | null;
}

// ============================================================================
// Loader functions
// ============================================================================

const ARTIFACTS_DIR = 'public/data/artifacts';

function loadArtifactJSON<T>(filename: string, warnings: string[]): T | null {
  try {
    const filepath = path.join(process.cwd(), ARTIFACTS_DIR, filename);
    
    if (!fs.existsSync(filepath)) {
      warnings.push(`Missing artifact: ${filename}`);
      return null;
    }
    
    const content = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(content) as T;
  } catch (error) {
    warnings.push(`Failed to load ${filename}: ${error}`);
    return null;
  }
}

export function loadArtifacts(): ArtifactsLoadResult {
  const warnings: string[] = [];
  
  // Load all artifacts
  const ready = loadArtifactJSON<ArtifactsReadyData>('ARTIFACTS_READY.json', warnings);
  const coverage = loadArtifactJSON<CoverageData>('coverage_v7.json', warnings);
  const scale = loadArtifactJSON<ScaleData>('scale_v7.json', warnings);
  const preview = loadArtifactJSON<PreviewRowData>('preview_row_v7.json', warnings);
  const sentiment = loadArtifactJSON<SentimentVsReturnData>('sentiment_vs_forward_return_v7.json', warnings);
  const regimes = loadArtifactJSON<RegimesData>('regimes_activity_vs_silence_v7.json', warnings);
  const hybrid = loadArtifactJSON<HybridDecisionsData>('hybrid_decisions_v7.json', warnings);
  const confidence = loadArtifactJSON<ConfidenceDisagreementData>('confidence_disagreement_v7.json', warnings);
  const lifecycle = loadArtifactJSON<LifecycleSummaryData>('lifecycle_summary_v7.json', warnings);
  
  return {
    available: warnings.length === 0,
    warnings,
    ready,
    coverage,
    scale,
    preview,
    sentiment,
    regimes,
    hybrid,
    confidence,
    lifecycle,
  };
}

// ============================================================================
// Utility functions
// ============================================================================

export function formatPercent(value: number | null | undefined): string {
  if (value === null || value === undefined) return '—';
  return `${(value * 100).toFixed(1)}%`;
}

export function formatNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return '—';
  return value.toLocaleString('en-US');
}

export function formatDuration(seconds: number | null | undefined): string {
  if (seconds === null || seconds === undefined) return '—';
  const hours = (seconds / 3600).toFixed(1);
  return `${hours}h`;
}

export function formatReturnPercent(value: number | null | undefined): string {
  if (value === null || value === undefined) return '—';
  const pct = (value * 100).toFixed(3);
  return pct.startsWith('-') ? pct : `+${pct}`;
}

// ============================================================================
// Phase 2A artifact loaders
// ============================================================================

export function loadActivityRegimes(): ActivityRegimesData | null {
  try {
    const filepath = path.join(process.cwd(), 'public/data/activity_regimes.json');
    
    if (!fs.existsSync(filepath)) {
      return null;
    }
    
    const content = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(content) as ActivityRegimesData;
  } catch (error) {
    console.error('Failed to load activity_regimes.json:', error);
    return null;
  }
}

export function loadSamplingDensity(): SamplingDensityData | null {
  try {
    const filepath = path.join(process.cwd(), 'public/data/sampling_density.json');
    
    if (!fs.existsSync(filepath)) {
      return null;
    }
    
    const content = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(content) as SamplingDensityData;
  } catch (error) {
    console.error('Failed to load sampling_density.json:', error);
    return null;
  }
}

export function loadSessionLifecycle(): SessionLifecycleData | null {
  try {
    const filepath = path.join(process.cwd(), 'public/data/session_lifecycle.json');
    
    if (!fs.existsSync(filepath)) {
      return null;
    }
    
    const content = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(content) as SessionLifecycleData;
  } catch (error) {
    console.error('Failed to load session_lifecycle.json:', error);
    return null;
  }
}
// Phase 3A loaders
export function loadDatasetOverview(): DatasetOverviewData | null {
  try {
    const filepath = path.join(process.cwd(), 'public/data/dataset_overview.json');
    
    if (!fs.existsSync(filepath)) {
      return null;
    }
    
    const content = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(content) as DatasetOverviewData;
  } catch (error) {
    console.error('Failed to load dataset_overview.json:', error);
    return null;
  }
}