/**
 * Status data loader and utilities for /status page
 * Reads from public/data/status.json (generated by CryptoBot exporter)
 */

export interface StatusData {
  last_updated_utc: string;
  archive_window: {
    first_day: string;
    last_day: string;
  };
  counts: {
    total_entries_scanned: number;
    v7_entries_seen: number;
    usable_entries: number;
    usable_full_spot_raw: number;
    usable_partial_spot_raw: number;
  };
  fail_reasons?: Record<string, unknown>;
}

export interface StatusDisplay {
  collectionStarted: string;
  daysRunning: number;
  totalRecords: number;
  lastUpdated: string;
  usableV7Percent: string;
  isAvailable: boolean;
}

/**
 * Validate that the JSON has the minimum required shape
 */
export function validateStatusData(data: unknown): data is StatusData {
  if (!data || typeof data !== 'object') return false;
  const d = data as Partial<StatusData>;
  
  return !!(
    d.last_updated_utc &&
    d.archive_window?.first_day &&
    d.archive_window?.last_day &&
    typeof d.counts?.usable_entries === 'number' &&
    typeof d.counts?.v7_entries_seen === 'number'
  );
}

/**
 * Format ISO date string to localized date
 */
export function formatDate(isoDateString: string): string {
  try {
    const date = new Date(isoDateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  } catch {
    return isoDateString;
  }
}

/**
 * Compute days running from first day to today
 * Returns (today - first_day) + 1
 */
export function computeDaysRunning(firstDay: string): number {
  try {
    const startDate = new Date(firstDay + 'T00:00:00Z');
    const today = new Date();
    // Reset time to midnight UTC for consistent calculation
    const todayUTC = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));
    const diffMs = todayUTC.getTime() - startDate.getTime();
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    return diffDays + 1; // +1 to include the start day
  } catch {
    return 0;
  }
}

/**
 * Compute usable v7 percentage
 * Returns formatted percentage string or "—" if not computable
 */
export function computeUsablePct(usableEntries: number, v7EntriesSeen: number): string {
  if (v7EntriesSeen === 0) return '—';
  const pct = (usableEntries / v7EntriesSeen) * 100;
  return pct.toFixed(1) + '%';
}

/**
 * Load and parse status data from the provided JSON object
 */
export function parseStatusData(data: unknown): StatusDisplay {
  if (!validateStatusData(data)) {
    return {
      collectionStarted: '—',
      daysRunning: 0,
      totalRecords: 0,
      lastUpdated: '—',
      usableV7Percent: '—',
      isAvailable: false,
    };
  }

  return {
    collectionStarted: formatDate(data.archive_window.first_day),
    daysRunning: computeDaysRunning(data.archive_window.first_day),
    totalRecords: data.counts.usable_entries,
    lastUpdated: formatDate(data.last_updated_utc),
    usableV7Percent: computeUsablePct(data.counts.usable_entries, data.counts.v7_entries_seen),
    isAvailable: true,
  };
}
